language: java
jdk:
  - openjdk8
branches:
  only:
    - main

before_install:
  - chmod +x gradlew

# Travis CI Server's Home
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-study
  - mkdir -p deploy
  - mv spring-study.zip deploy/spring-study.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dongha0940@naver.com